[theme]
base                     = "dark"
primaryColor             = "#00C805"
backgroundColor          = "#080C12"
secondaryBackgroundColor = "#0E1420"
textColor                = "#DDE6ED"
font                     = "sans serif"

[server]
headless = true
